Add related soong namespaces on SM7250
- the makefiles for the related modules were changed from Android.mk to Android.bp
- include soong namespaces for:
  vendor/qcom/sm7250/proprietary/data

Fix build break
error: "libconfigdb (SHARED_LIBRARIES android-arm64) missing libdsutils (SHARED_LIBRARIES android-arm64)"
error: "libqcrilNr  (SHARED_LIBRARIES android-arm64) missing libqdp     (SHARED_LIBRARIES android-arm64)"

Bug: 156322859
Change-Id: I62610660fcd9c1928514c7ce2d47d44f00db0a32